# Publish all joint states -----------------------------------
joint_state_controller:
   type: joint_state_controller/JointStateController
   publish_rate: 50  
  
# Position Controllers ---------------------------------------
rover_arm_eksen1_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: eksen1_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
rover_arm_eksen2_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: eksen2_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
rover_arm_eksen3_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: eksen3_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
rover_arm_eksen4_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: eksen4_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
rover_arm_eksen5_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: eksen5_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
rover_arm_eksen6_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: eksen6_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

rover_arm_controller:
  type: "effort_controllers/JointTrajectoryController"
  joints:
    - eksen1_joint
    - eksen2_joint
    - eksen3_joint
    - eksen4_joint
    - eksen5_joint
    - eksen6_joint
  gains: 
    eksen1_joint: {p: 100,  d: 10, i: 0.01, i_clamp: 1}
    eksen2_joint: {p: 100,  d: 10, i: 0.01, i_clamp: 1}
    eksen3_joint: {p: 100,  d: 10, i: 0.01, i_clamp: 1}
    eksen4_joint: {p: 100,  d: 10, i: 0.01, i_clamp: 1}
    eksen5_joint: {p: 100,  d: 10, i: 0.01, i_clamp: 1}
    eksen6_joint: {p: 100,  d: 10, i: 0.01, i_clamp: 1}
  constraints:
    eksen1_joint:
      goal: 0.1
    eksen2_joint:
      goal: 0.1
    eksen3_joint:
      goal: 0.1
    eksen4_joint:
      goal: 0.1
    eksen5_joint:
      goal: 0.1
    eksen6_joint:
      goal: 0.1
  goal_time: 100
